# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-08 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardsprojects',
            name='description',
        ),
    ]
